# Generated by Django 5.0 on 2023-12-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
