# Generated by Django 5.0 on 2023-12-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
