# Generated by Django 4.2.8 on 2023-12-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
